// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPopconfirm: typeof import('element-plus/es')['ElPopconfirm']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    Loading: typeof import('element-plus/es')['ElLoadingDirective']
    LoginForm: typeof import('./components/LoginForm.vue')['default']
    Navigation: typeof import('./components/Navigation.vue')['default']
    RegistrationForm: typeof import('./components/RegistrationForm.vue')['default']
    TaskBoard: typeof import('./components/TaskBoard.vue')['default']
    TaskCard: typeof import('./components/TaskCard.vue')['default']
    TaskCreateDialog: typeof import('./components/TaskCreateDialog.vue')['default']
    TaskForm: typeof import('./components/TaskForm.vue')['default']
    TaskList: typeof import('./components/TaskList.vue')['default']
    TaskStatusSelect: typeof import('./components/TaskStatusSelect.vue')['default']
    TaskUpdateDialog: typeof import('./components/TaskUpdateDialog.vue')['default']
  }
}

export { }
