// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    LoginForm: typeof import('./components/LoginForm.vue')['default']
    Navigation: typeof import('./components/Navigation.vue')['default']
    ProfileForm: typeof import('./components/ProfileForm.vue')['default']
    RegistrationForm: typeof import('./components/RegistrationForm.vue')['default']
    TaskBoard: typeof import('./components/TaskBoard.vue')['default']
    TaskCard: typeof import('./components/TaskCard.vue')['default']
    TaskCreateDialog: typeof import('./components/TaskCreateDialog.vue')['default']
    TaskForm: typeof import('./components/TaskForm.vue')['default']
    TaskList: typeof import('./components/TaskList.vue')['default']
    TaskStatusSelect: typeof import('./components/TaskStatusSelect.vue')['default']
    TaskUpdateDialog: typeof import('./components/TaskUpdateDialog.vue')['default']
  }
}

export { }
