version: '3'
vars:
  DB_URL: 'postgres://go_todo:go_todo@localhost:5432/go_todo?sslmode=disable'
tasks:
  migrations-create:
    cmds:
      - migrate create -dir migrations -ext sql {{.CLI_ARGS}}
  migrations-up:
    cmds:
      - migrate -path migrations -database '{{.DB_URL}}' up
  migrations-down:
    cmds:
      - migrate -path migrations -database '{{.DB_URL}}' down 1
  generate:
    cmds:
      - go generate ./...
  build:
    dir: deployment/compose
    cmds:
      - docker-compose build
  pull:
    dir: deployment/compose
    cmds:
      - docker-compose pull
  push:
    dir: deployment/compose
    cmds:
      - docker-compose push
  up:
    dir: deployment/compose
    cmds:
      - docker-compose up -d --no-build
  down:
    dir: deployment/compose
    cmds:
      - docker-compose down

  clean:
    dir: deployment/compose
    cmds:
      - docker-compose down --volume --remove-orphans
