version: '3'

tasks:
  go-run:
    desc: Run go command
    platforms: [ linux ]
    cmds:
      - go run ./cmd/main.go {{ .CLI_ARGS }}
  go-test:
    desc: Run test for golang app
    platforms: [ linux ]
    cmds:
      - go test ./... {{ .CLI_ARGS }}
  go-generate:
    desc: Generate go
    platforms: [ linux ]
    cmds:
      - go generate ./...
  dc:
    desc: Docker compose
    platforms: [ linux ]
    dir: deployment/compose
    cmds:
      - cp -n .env.dist .env
      - cp -n docker-compose.override.yml.dist docker-compose.override.yml
      - docker compose {{ .CLI_ARGS }}
  migrate-db-create-sql:
    desc: Migrate db - Create sql file
    platforms: [ linux ]
    cmds:
      - migrate create -ext sql -dir migrations/db -seq {{ .CLI_ARGS }}
  migrate-db:
    desc: Migrate db - Up/Down
    platforms: [ linux ]
    cmds:
      - migrate -database postgresql://user:secret@localhost:5432/db?sslmode=disable -path migrations/db {{ .CLI_ARGS }}
