version: '3'

tasks:
  run-api:
    desc: Run api runner
    cmds:
      - go run ./cmd/main.go api
  go-test:
    desc: Run test for golang app
    cmds:
      - go test ./...
  go-generate:
    desc: Generate go
    cmds:
      - go generate ./...
