basePath: /api/
definitions:
  models.Access:
    properties:
      groupId:
        type: integer
      id:
        type: integer
      projectId:
        type: integer
      role:
        type: string
      user:
        $ref: '#/definitions/models.User'
      userId:
        type: integer
    type: object
  models.Group:
    properties:
      id:
        type: integer
      members:
        items:
          $ref: '#/definitions/models.Access'
        type: array
      name:
        type: string
      projects:
        items:
          $ref: '#/definitions/models.Project'
        type: array
      status:
        type: string
    required:
    - name
    type: object
  models.Project:
    properties:
      group:
        $ref: '#/definitions/models.Group'
      groupId:
        type: integer
      id:
        type: integer
      members:
        items:
          $ref: '#/definitions/models.Access'
        type: array
      name:
        type: string
      status:
        type: string
      statuses:
        items:
          $ref: '#/definitions/models.ProjectStatus'
        type: array
    required:
    - name
    type: object
  models.ProjectStatus:
    properties:
      id:
        type: integer
      isFinal:
        type: boolean
      name:
        type: string
      projectId:
        type: integer
      sortOrder:
        type: integer
    type: object
  models.Task:
    properties:
      customStatus:
        $ref: '#/definitions/models.ProjectStatus'
      customStatusId:
        type: integer
      dateCreated:
        type: string
      description:
        type: string
      id:
        type: integer
      project:
        $ref: '#/definitions/models.Project'
      projectId:
        type: integer
      status:
        type: string
      title:
        type: string
      user:
        $ref: '#/definitions/models.User'
    required:
    - status
    - title
    type: object
  models.User:
    properties:
      email:
        type: string
      firstName:
        type: string
      id:
        type: integer
      lastName:
        type: string
      password:
        type: string
      status:
        type: string
    type: object
  schemas.AuthConfirmation:
    properties:
      token:
        type: string
    required:
    - token
    type: object
  schemas.AuthLoginRequest:
    properties:
      email:
        type: string
      password:
        type: string
    required:
    - email
    - password
    type: object
  schemas.AuthLoginResponse:
    properties:
      accessToken:
        type: string
      refreshToken:
        type: string
      user:
        $ref: '#/definitions/models.User'
    type: object
  schemas.AuthRefreshRequest:
    properties:
      refreshToken:
        type: string
    required:
    - refreshToken
    type: object
  schemas.AuthRefreshResponse:
    properties:
      accessToken:
        type: string
      refreshToken:
        type: string
      user:
        $ref: '#/definitions/models.User'
    type: object
  schemas.AuthRegistrationRequest:
    properties:
      email:
        type: string
      firstName:
        type: string
      lastName:
        type: string
      password:
        type: string
    required:
    - email
    - firstName
    - lastName
    - password
    type: object
  schemas.Error:
    properties:
      message: {}
      validationErrors: {}
    type: object
  schemas.GroupsListResponse:
    properties:
      items:
        items:
          $ref: '#/definitions/models.Group'
        type: array
      totalCount:
        type: integer
    type: object
  schemas.ProfilePasswordUpdate:
    properties:
      newPassword:
        type: string
      oldPassword:
        type: string
    required:
    - newPassword
    - oldPassword
    type: object
  schemas.ProfileUpdate:
    properties:
      firstName:
        type: string
      lastName:
        type: string
    required:
    - firstName
    - lastName
    type: object
  schemas.ProjectsListResponse:
    properties:
      items:
        items:
          $ref: '#/definitions/models.Project'
        type: array
      totalCount:
        type: integer
    type: object
  schemas.TasksListResponse:
    properties:
      items:
        items:
          $ref: '#/definitions/models.Task'
        type: array
      totalCount:
        type: integer
    type: object
host: localhost
info:
  contact: {}
  description: gotodo api
  title: gotodo
  version: "1.0"
paths:
  /auth/confirmation/:
    post:
      consumes:
      - application/json
      description: User confirmation after registration
      parameters:
      - description: Request body
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/schemas.AuthConfirmation'
      produces:
      - application/json
      responses:
        "204":
          description: ""
        "400":
          description: Validation error
          schema:
            $ref: '#/definitions/schemas.Error'
        "500":
          description: Server error
          schema:
            $ref: '#/definitions/schemas.Error'
      summary: Confirmation
      tags:
      - auth
  /auth/login/:
    post:
      consumes:
      - application/json
      description: Login in new sessions
      parameters:
      - description: Request data
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/schemas.AuthLoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/schemas.AuthLoginResponse'
        "400":
          description: Validation error
          schema:
            $ref: '#/definitions/schemas.Error'
        "500":
          description: Server error
          schema:
            $ref: '#/definitions/schemas.Error'
      summary: Login
      tags:
      - auth
  /auth/refresh/:
    post:
      consumes:
      - application/json
      description: Refresh exists session
      parameters:
      - description: Request data
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/schemas.AuthRefreshRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/schemas.AuthRefreshResponse'
        "400":
          description: Validation error
          schema:
            $ref: '#/definitions/schemas.Error'
        "500":
          description: Server error
          schema:
            $ref: '#/definitions/schemas.Error'
      summary: Refresh
      tags:
      - auth
  /auth/registration/:
    post:
      consumes:
      - application/json
      description: Register new user
      parameters:
      - description: Request body
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/schemas.AuthRegistrationRequest'
      produces:
      - application/json
      responses:
        "201":
          description: ""
        "400":
          description: Validation error
          schema:
            $ref: '#/definitions/schemas.Error'
        "500":
          description: Server error
          schema:
            $ref: '#/definitions/schemas.Error'
      summary: Registration
      tags:
      - auth
  /groups/:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/schemas.GroupsListResponse'
            type: array
        "500":
          description: Server error
          schema:
            $ref: '#/definitions/schemas.Error'
      security:
      - ApiHeaderAuth: []
      summary: List
      tags:
      - groups
    post:
      consumes:
      - application/json
      description: Create a new group
      parameters:
      - description: Request body
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/models.Group'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Group'
        "400":
          description: Validation error
          schema:
            $ref: '#/definitions/schemas.Error'
        "500":
          description: Server error
          schema:
            $ref: '#/definitions/schemas.Error'
      security:
      - ApiHeaderAuth: []
      summary: Create
      tags:
      - groups
  /groups/{id}/:
    delete:
      consumes:
      - application/json
      description: Delete group
      parameters:
      - description: Group identifier
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "204":
          description: ""
        "404":
          description: ""
        "500":
          description: Server error
          schema:
            $ref: '#/definitions/schemas.Error'
      security:
      - ApiHeaderAuth: []
      summary: Delete
      tags:
      - groups
    get:
      consumes:
      - application/json
      description: Get group detail
      parameters:
      - description: Group identifier
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Group'
        "404":
          description: ""
        "500":
          description: Server error
          schema:
            $ref: '#/definitions/schemas.Error'
      security:
      - ApiHeaderAuth: []
      summary: Retrieve
      tags:
      - groups
    put:
      consumes:
      - application/json
      description: Update group
      parameters:
      - description: Group identifier
        in: path
        name: id
        required: true
        type: integer
      - description: Request body
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/models.Group'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Group'
        "400":
          description: Validation error
          schema:
            $ref: '#/definitions/schemas.Error'
        "500":
          description: Server error
          schema:
            $ref: '#/definitions/schemas.Error'
      security:
      - ApiHeaderAuth: []
      summary: Update
      tags:
      - groups
  /profile/:
    get:
      consumes:
      - application/json
      description: Get profile
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.User'
        "500":
          description: Server error
          schema:
            $ref: '#/definitions/schemas.Error'
      security:
      - ApiHeaderAuth: []
      summary: Retrieve
      tags:
      - profile
    put:
      consumes:
      - application/json
      parameters:
      - description: Request body
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/schemas.ProfileUpdate'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.User'
        "500":
          description: Server error
          schema:
            $ref: '#/definitions/schemas.Error'
      security:
      - ApiHeaderAuth: []
      summary: Update
      tags:
      - profile
  /profile/password/:
    put:
      consumes:
      - application/json
      parameters:
      - description: Request body
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/schemas.ProfilePasswordUpdate'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.User'
        "500":
          description: Server error
          schema:
            $ref: '#/definitions/schemas.Error'
      security:
      - ApiHeaderAuth: []
      summary: Password Update
      tags:
      - profile
  /projects/:
    get:
      consumes:
      - application/json
      parameters:
      - in: query
        name: groupID
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/schemas.ProjectsListResponse'
            type: array
        "500":
          description: Server error
          schema:
            $ref: '#/definitions/schemas.Error'
      security:
      - ApiHeaderAuth: []
      summary: List
      tags:
      - projects
    post:
      consumes:
      - application/json
      description: Create a new project
      parameters:
      - description: Request body
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/models.Project'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Project'
        "400":
          description: Validation error
          schema:
            $ref: '#/definitions/schemas.Error'
        "500":
          description: Server error
          schema:
            $ref: '#/definitions/schemas.Error'
      security:
      - ApiHeaderAuth: []
      summary: Create
      tags:
      - projects
  /projects/{id}/:
    delete:
      consumes:
      - application/json
      description: Delete project
      parameters:
      - description: Group identifier
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "204":
          description: ""
        "404":
          description: ""
        "500":
          description: Server error
          schema:
            $ref: '#/definitions/schemas.Error'
      security:
      - ApiHeaderAuth: []
      summary: Delete
      tags:
      - projects
    get:
      consumes:
      - application/json
      description: Get project detail
      parameters:
      - description: Group identifier
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Project'
        "404":
          description: ""
        "500":
          description: Server error
          schema:
            $ref: '#/definitions/schemas.Error'
      security:
      - ApiHeaderAuth: []
      summary: Retrieve
      tags:
      - projects
    put:
      consumes:
      - application/json
      description: Update project
      parameters:
      - description: Group identifier
        in: path
        name: id
        required: true
        type: integer
      - description: Request body
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/models.Project'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Project'
        "400":
          description: Validation error
          schema:
            $ref: '#/definitions/schemas.Error'
        "500":
          description: Server error
          schema:
            $ref: '#/definitions/schemas.Error'
      security:
      - ApiHeaderAuth: []
      summary: Update
      tags:
      - projects
  /tasks/:
    get:
      consumes:
      - application/json
      description: Get tasks list
      parameters:
      - in: query
        name: projectID
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/schemas.TasksListResponse'
        "500":
          description: Server error
          schema:
            $ref: '#/definitions/schemas.Error'
      security:
      - ApiHeaderAuth: []
      summary: List
      tags:
      - tasks
    post:
      consumes:
      - application/json
      description: Create new tasks
      parameters:
      - description: Request body
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/models.Task'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/models.Task'
        "400":
          description: Validation error
          schema:
            $ref: '#/definitions/schemas.Error'
        "500":
          description: Server error
          schema:
            $ref: '#/definitions/schemas.Error'
      security:
      - ApiHeaderAuth: []
      summary: Create
      tags:
      - tasks
  /tasks/{id}/:
    delete:
      consumes:
      - application/json
      description: Delete task
      parameters:
      - description: Task identifier
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "204":
          description: ""
        "404":
          description: ""
        "500":
          description: Server error
          schema:
            $ref: '#/definitions/schemas.Error'
      security:
      - ApiHeaderAuth: []
      summary: Delete
      tags:
      - tasks
    get:
      consumes:
      - application/json
      description: Get task details
      parameters:
      - description: Task identifier
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Task'
        "404":
          description: ""
        "500":
          description: Server error
          schema:
            $ref: '#/definitions/schemas.Error'
      security:
      - ApiHeaderAuth: []
      summary: Retrieve
      tags:
      - tasks
    put:
      consumes:
      - application/json
      description: Update task
      parameters:
      - description: Task identifier
        in: path
        name: id
        required: true
        type: integer
      - description: Request body
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/models.Task'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Task'
        "400":
          description: Validation error
          schema:
            $ref: '#/definitions/schemas.Error'
        "500":
          description: Server error
          schema:
            $ref: '#/definitions/schemas.Error'
      security:
      - ApiHeaderAuth: []
      summary: Update
      tags:
      - tasks
securityDefinitions:
  ApiKeyHeader:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
tags:
- description: Auth endpoint
  name: auth
- description: Groups endpoint
  name: groups
- description: Projects endpoint
  name: projects
- description: Tasks endpoint
  name: tasks
- description: Profile endpoint
  name: profile
