basePath: /
definitions:
  models.Task:
    properties:
      body:
        type: string
      dateCreated:
        type: string
      id:
        type: integer
      isDone:
        type: boolean
      title:
        type: string
    type: object
  schemas.Error:
    properties:
      details:
        type: string
      message:
        type: string
      validationErrors:
        additionalProperties:
          items:
            type: string
          type: array
        type: object
    type: object
  schemas.TaskForm:
    properties:
      body:
        type: string
      title:
        type: string
    required:
    - title
    type: object
host: localhost
info:
  contact: {}
  description: API for gotodo
  title: gotodo
  version: "1.0"
paths:
  /tasks/:
    get:
      parameters:
      - in: query
        name: limit
        type: integer
      - in: query
        name: offset
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Task'
            type: array
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/schemas.Error'
      summary: List
      tags:
      - Tasks
    post:
      consumes:
      - application/json
      parameters:
      - description: Request body
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/schemas.TaskForm'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/models.Task'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/schemas.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/schemas.Error'
      summary: Create
      tags:
      - Tasks
  /tasks/{id}:
    put:
      consumes:
      - application/json
      parameters:
      - description: Task ID
        in: path
        name: id
        required: true
        type: integer
      - description: Request body
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/schemas.TaskForm'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/models.Task'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/schemas.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/schemas.Error'
      summary: Update
      tags:
      - Tasks
swagger: "2.0"
tags:
- description: Endpoint tasks
  name: Tasks
