basePath: /
host: localhost
info:
  contact: {}
  description: API for gotodo
  title: gotodo
  version: "1.0"
paths:
  /tasks/:
    get:
      responses: {}
      summary: List
    post:
      responses: {}
      summary: Create
swagger: "2.0"
